import pygame


def main():
    print('Starting Game')

    print('Initialising PyGame')
    pygame.init()  # Required by every PyGame application

    print('Initialising HelloWorldGame')
    pygame.display.set_mode((200, 100))  # Note that this takes a tuple specifying the width and highet of the display
    pygame.display.set_caption('Hello World')
    print('Update display')
    pygame.display.update()

    print('Starting main Game Playing Loop')
    running = True
    while running:
        for event in pygame.event.get():
            # There are lots of events generated by we are only interested on the Quit event
            if event.type == pygame.QUIT:
                print('Received Quit Event:', event)
                running = False

    print('Game Over')
    # Now tidy up and quit Python
    pygame.quit()


if __name__ == '__main__':
    main()
